version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: duktape
    versions:
    - 2.3.0.0
